apiVersion: v1
kind: Pod
metadata:
  name: demo
  namespace: pod-id
  labels:
    aadpodidbinding: pod-id-euw-aks-bld-2202
spec:
  containers:
  - name: demo
    image: mcr.microsoft.com/oss/azure/aad-pod-identity/demo:v1.6.3
    args:
      - --subscriptionid=9b5d7944-a55e-40f5-bb86-3f7b81dc13ba
      - --clientid=6fbfabc5-dde7-4091-af76-b47fa36e29cb
      - --resourcegroup=rg-euw-aks-bld-2202
    env:
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
  nodeSelector:
    kubernetes.io/os: linux